# CREATE  DATA BASE
CREATE TABLE `PLATFORM_USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
  `AGE` INT(11) NOT NULL COMMENT '年龄',
  `CTM` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

#  INSET DATA TO DATABASE TABLE
INSERT INTO `PLATFORM_USER` (`USERNAME`, `AGE`, `CTM`) VALUES('张三', '18', NOW()) ;
INSERT INTO `PLATFORM_USER` (`USERNAME`, `AGE`, `CTM`) VALUES('李四', '20', NOW()) ;
INSERT INTO `PLATFORM_USER` (`USERNAME`, `AGE`, `CTM`) VALUES('王五', '19', NOW()) ;